openapi: 3.0.0
info:
  title: "API_ResidentService"
  description: "API Services"
  version: "20250604083445"
servers:
  - url: http://localhost:8082/Comforta_version2DevelopmentNETPostgreSQL/api
paths:
components:
  securitySchemes:
    oAuthGXGAM:
      type: oauth2
      description: GAM OAuth 2
      flows:
        password:          
          tokenUrl: http://localhost:8082/Comforta_version2DevelopmentNETPostgreSQL/oauth/gam/v2.0/access_token
          scopes: 
            fullcontrol: Full access

  schemas:
  
 
